--- #YAML:1.0
name:               HTTP-SimpleLinkChecker
version:            1.16
abstract:           Check the HTTP response code for a link
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request:   1.28
    HTTP::Status:    0
    LWP::UserAgent:  1.09
resources:
    homepage:    http://github.com/briandfoy/http-simplelinkchecker
    repository:  git://github.com/briandfoy/http-simplelinkchecker.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
